/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicHomeRouteImport } from './routes/_public/_home'
import { Route as PublicHomeIndexRouteImport } from './routes/_public/_home/index'

const PublicHomeRoute = PublicHomeRouteImport.update({
  id: '/_public/_home',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicHomeIndexRoute = PublicHomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicHomeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicHomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicHomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public/_home': typeof PublicHomeRouteWithChildren
  '/_public/_home/': typeof PublicHomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/_public/_home' | '/_public/_home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicHomeRoute: typeof PublicHomeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public/_home': {
      id: '/_public/_home'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/_home/': {
      id: '/_public/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicHomeIndexRouteImport
      parentRoute: typeof PublicHomeRoute
    }
  }
}

interface PublicHomeRouteChildren {
  PublicHomeIndexRoute: typeof PublicHomeIndexRoute
}

const PublicHomeRouteChildren: PublicHomeRouteChildren = {
  PublicHomeIndexRoute: PublicHomeIndexRoute,
}

const PublicHomeRouteWithChildren = PublicHomeRoute._addFileChildren(
  PublicHomeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicHomeRoute: PublicHomeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
